#!/usr/bin/env node

/**
 * ============================================================================
 * 🔄 update-stats.js — README Auto-Composer
 * ============================================================================
 *
 * Reads all markdown component files from /components in a defined order,
 * concatenates them with proper spacing, and writes the result to README.md.
 *
 * Run by the update-readme.yml GitHub Actions workflow on every push to main.
 *
 * Usage:
 *   node scripts/update-stats.js
 *
 * Component Order:
 *   1. hero.md        — Header banner, typing animation, social badges
 *   2. about.md       — Bio and highlights
 *   3. tech-stack.md  — Skill badges grid
 *   4. stats.md       — GitHub stats cards and graphs
 *   5. projects.md    — Featured project cards
 *   6. achievements.md— Trophies and certifications
 *   7. quote.md       — Dev quote widget
 *   8. contact.md     — Social connection links
 *   9. footer.md      — Footer banner and visitor counter
 *
 * ============================================================================
 */

const fs = require("fs");
const path = require("path");

// ── Configuration ────────────────────────────────────────────────────────────

/**
 * Ordered list of component filenames.
 * Components are composed into README.md in this exact order.
 * Add, remove, or reorder entries to customize the final README layout.
 */
const COMPONENT_ORDER = [
  "hero.md",
  "about.md",
  "tech-stack.md",
  "stats.md",
  "projects.md",
  "achievements.md",
  "quote.md",
  "contact.md",
  "footer.md",
];

/** Directory containing the markdown component files */
const COMPONENTS_DIR = path.join(__dirname, "..", "components");

/** Output file path */
const OUTPUT_FILE = path.join(__dirname, "..", "README.md");

/** Separator between components (blank lines for clean markdown rendering) */
const SECTION_SEPARATOR = "\n\n";

// ── Auto-generated header comment ────────────────────────────────────────────

const HEADER_COMMENT = `<!-- ============================================================================
     🚀 AUTO-GENERATED README
     ============================================================================
     This file is automatically composed from /components by scripts/update-stats.js.
     Do NOT edit this file directly — edit individual component files instead.
     
     Last updated: ${new Date().toISOString()}
     Components: ${COMPONENT_ORDER.join(", ")}
     ============================================================================ -->

`;

// ── Main Compose Function ────────────────────────────────────────────────────

/**
 * Reads each component file in order and concatenates them into a single
 * README.md string. Missing files are logged as warnings but do not halt
 * the build — the README is still generated with available components.
 *
 * @returns {string} The composed README content.
 */
function composeReadme() {
  console.log("📝 Composing README.md from components...\n");

  const sections = [];
  let successCount = 0;
  let warningCount = 0;

  for (const filename of COMPONENT_ORDER) {
    const filepath = path.join(COMPONENTS_DIR, filename);

    if (!fs.existsSync(filepath)) {
      console.warn(`  ⚠️  Missing component: ${filename} — skipping`);
      warningCount++;
      continue;
    }

    try {
      const content = fs.readFileSync(filepath, "utf-8").trim();
      sections.push(content);
      console.log(`  ✅ Loaded: ${filename} (${content.length} chars)`);
      successCount++;
    } catch (err) {
      console.error(`  ❌ Error reading ${filename}: ${err.message}`);
      warningCount++;
    }
  }

  console.log(
    `\n📊 Summary: ${successCount} loaded, ${warningCount} warnings\n`
  );

  return HEADER_COMMENT + sections.join(SECTION_SEPARATOR) + "\n";
}

// ── Write Output ─────────────────────────────────────────────────────────────

/**
 * Writes the composed README content to the output file.
 * Creates a backup of the existing README before overwriting.
 */
function writeReadme(content) {
  // Create backup if README exists
  if (fs.existsSync(OUTPUT_FILE)) {
    const backupPath = OUTPUT_FILE + ".bak";
    fs.copyFileSync(OUTPUT_FILE, backupPath);
    console.log(`💾 Backup saved: README.md.bak`);
  }

  fs.writeFileSync(OUTPUT_FILE, content, "utf-8");
  console.log(`✨ README.md written successfully (${content.length} chars)`);
  console.log(`📁 Output: ${OUTPUT_FILE}\n`);
}

// ── Entry Point ──────────────────────────────────────────────────────────────

try {
  const readme = composeReadme();
  writeReadme(readme);
  console.log("🎉 Done! README.md is ready.\n");
  process.exit(0);
} catch (err) {
  console.error(`\n💥 Fatal error: ${err.message}`);
  console.error(err.stack);
  process.exit(1);
}
